### ISSUE TITLE
Issue tracker URL in metadata

### ISSUE THREAD

**Issue by dimus** [CatalogueOfLife/coldp#86] opened 2024-11-04 10:56 UTC
It would be beneficial to have a URL field to a project's issue tracker. It would help to streamline and speedup problems reporting and solving.

**Comment by mdoering** [comment] 2024-11-04 14:35
duplicate of https://github.com/CatalogueOfLife/coldp/issues/80

**Closed by mdoering** 2024-11-04 14:35 UTC
Labels: duplicate
